Repository maqsoftware/Pehla-School, pull requests merged in 2019-08, with the labels that each got.

#262 Added urdu text in Language Manager
  pehlaschool/Classes/Managers/LanguageManager.cpp
Labels: bug

#263 Added Great and Tutorial Trace
  pehlaschool/Classes/Managers/LanguageManager.cpp
Labels: bug

#264 Fix strings in LanguageManager.cpp
  pehlaschool/Classes/Managers/LanguageManager.cpp
Labels: bug

#265 Fix OBB version
  pehlaschool/proj.android-studio/app/AndroidManifest.xml
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/DownloadExpansionFile.java
Labels: bug

#276 Logic to load and pass parameters specific to the locale
  pehlaschool/Classes/AppDelegate.cpp
  pehlaschool/Classes/Managers/LanguageManager.cpp
  pehlaschool/Classes/Managers/LanguageManager.hpp
  pehlaschool/proj.android-studio/app/AndroidManifest.xml
  pehlaschool/proj.android-studio/app/build.gradle
  pehlaschool/proj.android-studio/app/src/bengali/AndroidManifest.xml
  pehlaschool/proj.android-studio/app/src/bengali/res/values/strings.xml
  pehlaschool/proj.android-studio/app/src/english/AndroidManifest.xml
  pehlaschool/proj.android-studio/app/src/english/res/values/strings.xml
  pehlaschool/proj.android-studio/app/src/hindi/AndroidManifest.xml
  pehlaschool/proj.android-studio/app/src/hindi/res/values/strings.xml
  pehlaschool/proj.android-studio/app/src/main/res/values/strings.xml
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/AppActivity.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/PehlaSchoolApplication.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/VoiceMoldManager.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/drawingcoloring/activity/DrawingColoringActivity.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/maq/kitkitProvider/Fish.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/maq/kitkitProvider/KitkitDBHandler.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/maq/kitkitProvider/KitkitProvider.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/maq/kitkitProvider/SntpResult.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/maq/kitkitProvider/User.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/maq/kitkitlogger/KitKitLogger.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/maq/kitkitlogger/KitKitLoggerActivity.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/maq/kitkitlogger/KitkitContextWrapper.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/AboutActivity.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/AdministrationActivity.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/CreditActivity.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/MainActivity.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/RenameUserDialog.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/SelectUserDialogFragment.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/SettingActivity.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/SntpUpdater.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/ToolsActivity.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/UserNameActivity.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/UserNameListDialog.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/Util.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/VideoPlayerActivity.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/activity/GalleryActivity.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/activity/base/BaseActivity.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/core/GalleryApplication.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/writingboard/activity/MainActivity.java
  pehlaschool/proj.android-studio/app/src/urdu/AndroidManifest.xml
  pehlaschool/proj.android-studio/app/src/urdu/res/values/strings.xml
  pehlaschool/proj.android-studio/settings.gradle
Labels: enhancement

#278 Move version code and name to productFlavor block
  pehlaschool/proj.android-studio/app/AndroidManifest.xml
  pehlaschool/proj.android-studio/app/build.gradle
Labels: enhancement

#279 Fix Library call intent parameter issue
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/pehlalauncher/MainActivity.java
Labels: bug

#284 Fix TTS issue for Hindi numbers in Math section
  pehlaschool/Classes/Games/EggQuiz/EggQuizScene.cpp
Labels: bug

#269 Update INSTALL.md and README.md
  INSTALL.md
  README.md
  pehlaschool/README
  pehlaschool/README.md
  pehlaschoollibrary/README.md
  voice-engine-a/README
  voice-engine-a/README.md
Labels: documentation

#275 Add steps to localize the language of the app
  LOCALIZE.md
Labels: documentation

#298 Update the Urdu text in the LanguageManager.cpp file
  pehlaschool/Classes/Managers/LanguageManager.cpp
Labels: enhancement

#299 Update version name and Bengali text
  pehlaschool/Classes/Managers/LanguageManager.cpp
  pehlaschool/proj.android-studio/app/build.gradle
  pehlaschool/proj.android-studio/app/src/bengali/res/values/strings.xml
Labels: enhancement

#312 Updated font family and size for coin count and level label
  pehlaschool/Classes/Common/Controls/CoinTab.cpp
  pehlaschool/Classes/Menu/DailyScene2.cpp
Labels: bug, enhancement

#315 Update LICENSE
  LICENSE
Labels: documentation, enhancement

#292 Added code to fix the locale issue in the Pehla School Library
  pehlaschoollibrary/Classes/BookView.cpp
  pehlaschoollibrary/Classes/BookView.hpp
  pehlaschoollibrary/Classes/Common/Controls/CompletePopup.cpp
  pehlaschoollibrary/proj.android-studio/app/AndroidManifest.xml
  pehlaschoollibrary/proj.android-studio/app/main/AndroidManifest.xml
  pehlaschoollibrary/proj.android-studio/app/src/org/cocos2dx/cpp/AppActivity.java
Labels: bug

#286 Change locale of the Pehla School Library in runtime
  pehlaschoollibrary/proj.android-studio/app/res/layout/activity_splash_screen.xml
  pehlaschoollibrary/proj.android-studio/app/res/values-bn/strings.xml
  pehlaschoollibrary/proj.android-studio/app/res/values-hi/strings.xml
  pehlaschoollibrary/proj.android-studio/app/res/values-ur/strings.xml
  pehlaschoollibrary/proj.android-studio/app/res/values/strings.xml
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/pehlaschool/library/MainActivity.java
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/pehlaschool/library/SelectActivity.java
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/pehlaschool/library/SplashScreenActivity.java
Labels: enhancement

#318 Update version code for Bengali build
  pehlaschool/proj.android-studio/app/build.gradle
Labels: bug

#289 Merged kitkitschoollogger module into Library app
  kitkitschoollogger/build.gradle
  kitkitschoollogger/gradle.properties
  kitkitschoollogger/gradle/wrapper/gradle-wrapper.jar
  kitkitschoollogger/gradle/wrapper/gradle-wrapper.properties
  kitkitschoollogger/gradlew
  kitkitschoollogger/gradlew.bat
  kitkitschoollogger/kitkitlogger/.gitignore
  kitkitschoollogger/kitkitlogger/build.gradle
  kitkitschoollogger/kitkitlogger/proguard-rules.pro
  kitkitschoollogger/kitkitlogger/src/main/AndroidManifest.xml
  kitkitschoollogger/settings.gradle
  pehlaschoollibrary/Classes/BookView.cpp
  pehlaschoollibrary/proj.android-studio/app/build.gradle
  pehlaschoollibrary/proj.android-studio/app/main/AndroidManifest.xml
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/kitkitProvider/Fish.java
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/kitkitProvider/KitkitDBHandler.java
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/kitkitProvider/KitkitProvider.java
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/kitkitProvider/SntpResult.java
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/kitkitProvider/User.java
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/kitkitlogger/KitKitLogger.java
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/kitkitlogger/KitKitLoggerActivity.java
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/kitkitlogger/KitkitContextWrapper.java
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/pehlaschool/library/DownloadExpansionFile.java
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/pehlaschool/library/MainActivity.java
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/pehlaschool/library/SelectActivity.java
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/pehlaschool/library/SplashScreenActivity.java
  pehlaschoollibrary/proj.android-studio/settings.gradle
Labels: enhancement

#320 Fixed the locale based SplashScreenBackground issue
  pehlaschoollibrary/proj.android-studio/app/res/drawable-bn-hdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-bn-mdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-bn-xhdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-bn-xxhdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-bn-xxxhdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-hi-hdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-hi-mdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-hi-xhdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-hi-xxhdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-hi-xxxhdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-ur-hdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-ur-mdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-ur-xhdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-ur-xxhdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-ur-xxxhdpi/splash_screen_background.png
Labels: bug

#306 Updated the games name for the English and Hindi Build
  pehlaschool/Classes/Managers/LanguageManager.cpp
Labels: enhancement
