Repository maqsoftware/Pehla-School, pull requests merged in 2019-07, with the labels that each got.

#116 Sync statistics with the Firebase
  .gitignore
  launcher/app/build.gradle
  launcher/app/src/main/java/com/maq/xprize/kitkitlauncher/hindi/MainActivity.java
  launcher/build.gradle
  mainapp/Classes/CCAppController.cpp
  mainapp/proj.android-studio/app/build.gradle
  mainapp/proj.android-studio/app/src/org/cocos2dx/cpp/AppActivity.java
  mainapp/proj.android-studio/build.gradle
Labels: enhancement

#121 Fix the empty If statement to a negative condition If statement
  bookviewer/proj.android-studio/app/src/org/cocos2dx/cpp/AppActivity.java
Labels: enhancement

#128 Updated the version and OBB length
  bookviewer/proj.android-studio/app/build.gradle
  bookviewer/proj.android-studio/app/main/AndroidManifest.xml
  bookviewer/proj.android-studio/app/src/com/maq/xprize/kitkitlibrary/english/SplashScreenActivity.java
  bookviewer/proj.android-studio/app/src/kitkitschool/DownloadExpansionFile.java
  mainapp/proj.android-studio/app/AndroidManifest.xml
  mainapp/proj.android-studio/app/build.gradle
  mainapp/proj.android-studio/app/src/kitkitschool/DownloadExpansionFile.java
Labels: bug

#132 Update EggQuizScene.cpp
  mainapp/Classes/Games/EggQuiz/EggQuizScene.cpp
  mainapp/proj.android-studio/app/src/kitkitschool/DownloadExpansionFile.java
Labels: bug

#144 Update Library app Play Store URL
  mainapp/proj.android-studio/app/build.gradle
  mainapp/proj.android-studio/app/src/org/cocos2dx/cpp/kitkitlauncher/hindi/VideoPlayerActivity.java
Labels: minor fix

#154 Change Library app's package name based on Pehla School title
  bookviewer/Classes/AppDelegate.cpp
  bookviewer/proj.android-studio/app/AndroidManifest.xml
  bookviewer/proj.android-studio/app/build.gradle
  bookviewer/proj.android-studio/app/debug/AndroidManifest.xml
  bookviewer/proj.android-studio/app/main/AndroidManifest.xml
  bookviewer/proj.android-studio/app/release/AndroidManifest.xml
  bookviewer/proj.android-studio/app/res/layout/activity_main.xml
  bookviewer/proj.android-studio/app/res/layout/activity_select.xml
  bookviewer/proj.android-studio/app/res/layout/activity_video_player.xml
  bookviewer/proj.android-studio/app/res/layout/dialog_video.xml
  bookviewer/proj.android-studio/app/res/values-sw/strings.xml
  bookviewer/proj.android-studio/app/res/values/strings.xml
  bookviewer/proj.android-studio/app/src/com/maq/pehlaschool/library/BookDetailActivity.java
  bookviewer/proj.android-studio/app/src/com/maq/pehlaschool/library/CustomViewPager.java
  bookviewer/proj.android-studio/app/src/com/maq/pehlaschool/library/MainActivity.java
  bookviewer/proj.android-studio/app/src/com/maq/pehlaschool/library/SelectActivity.java
  bookviewer/proj.android-studio/app/src/com/maq/pehlaschool/library/SplashScreenActivity.java
  bookviewer/proj.android-studio/app/src/com/maq/pehlaschool/library/TutorialVideoPopupView.java
  bookviewer/proj.android-studio/app/src/com/maq/pehlaschool/library/Util.java
  bookviewer/proj.android-studio/app/src/com/maq/pehlaschool/library/VideoControllerView.java
  bookviewer/proj.android-studio/app/src/com/maq/pehlaschool/library/VideoPlayerActivity.java
  bookviewer/proj.android-studio/app/src/kitkitschool/DownloadExpansionFile.java
  bookviewer/proj.android-studio/app/src/utils/Zip.java
  bookviewer/proj.android-studio/settings.gradle
  kitkitschoollogger/kitkitlogger/src/main/java/com/maq/kitkitProvider/KitkitProvider.java
  kitkitschoollogger/kitkitlogger/src/main/java/com/maq/kitkitlogger/KitKitLoggerActivity.java
Labels: enhancement

#173 Update Kitkit School image with Pehla School image
  mainapp/proj.android-studio/app/res/layout/activity_main.xml
  mainapp/proj.android-studio/app/src/main/res/drawable-nodpi/launcher_kitkitschool_logo_phase02.png
  mainapp/proj.android-studio/app/src/main/res/drawable-nodpi/launcher_kitkitschool_logo_phase021.png
  mainapp/proj.android-studio/app/src/main/res/drawable-nodpi/launcher_kitkitschool_logo_phase03.png
  mainapp/proj.android-studio/app/src/main/res/drawable-nodpi/launcher_kitkitschool_logo_phase031.png
  mainapp/proj.android-studio/app/src/main/res/drawable-nodpi/launcher_pehlaschool_logo.png
  mainapp/proj.android-studio/app/src/main/res/drawable/launcher_kitkitschool_logo.png
  mainapp/proj.android-studio/app/src/main/res/drawable/launcher_kitkitschool_logo2.png
Labels: enhancement

#188 Updated text layout to auto-scale based on device resolution
  bookviewer/proj.android-studio/app/build.gradle
  bookviewer/proj.android-studio/app/res/layout/activity_select.xml
  bookviewer/proj.android-studio/app/res/values/strings.xml
Labels: bug

#189 Updated icons and patch file size
  bookviewer/proj.android-studio/app/res/mipmap-hdpi/ic_launcher.png
  bookviewer/proj.android-studio/app/res/mipmap-mdpi/ic_launcher.png
  bookviewer/proj.android-studio/app/res/mipmap-xhdpi/ic_launcher.png
  bookviewer/proj.android-studio/app/res/mipmap-xxhdpi/ic_launcher.png
  bookviewer/proj.android-studio/app/res/mipmap-xxxhdpi/ic_launcher.png
  mainapp/proj.android-studio/app/AndroidManifest.xml
  mainapp/proj.android-studio/app/res/mipmap-hdpi/ic_launcher.png
  mainapp/proj.android-studio/app/res/mipmap-mdpi/ic_launcher.png
  mainapp/proj.android-studio/app/res/mipmap-xhdpi/ic_launcher.png
  mainapp/proj.android-studio/app/res/mipmap-xxhdpi/ic_launcher.png
  mainapp/proj.android-studio/app/res/mipmap-xxxhdpi/ic_launcher.png
  mainapp/proj.android-studio/app/src/org/cocos2dx/cpp/DownloadExpansionFile.java
Labels: enhancement

#190 Update Library language based on the calling intent
  bookviewer/proj.android-studio/app/main/AndroidManifest.xml
  bookviewer/proj.android-studio/app/res/drawable-hdpi/splash_screen_background_urdu.png
  bookviewer/proj.android-studio/app/res/drawable-mdpi/splash_screen_background_urdu.png
  bookviewer/proj.android-studio/app/res/drawable-xhdpi/splash_screen_background_urdu.png
  bookviewer/proj.android-studio/app/res/drawable-xxhdpi/splash_screen_background_urdu.png
  bookviewer/proj.android-studio/app/res/drawable-xxxhdpi/splash_screen_background_urdu.png
  bookviewer/proj.android-studio/app/res/layout/activity_main.xml
  bookviewer/proj.android-studio/app/res/layout/activity_select.xml
  bookviewer/proj.android-studio/app/res/layout/activity_splash_screen.xml
  bookviewer/proj.android-studio/app/res/values/strings.xml
  bookviewer/proj.android-studio/app/src/com/maq/pehlaschool/library/MainActivity.java
  bookviewer/proj.android-studio/app/src/com/maq/pehlaschool/library/SelectActivity.java
  bookviewer/proj.android-studio/app/src/com/maq/pehlaschool/library/SplashScreenActivity.java
  bookviewer/proj.android-studio/app/src/kitkitschool/DownloadExpansionFile.java
Labels: enhancement

#196 Updated book resource path
  bookviewer/Classes/AppDelegate.cpp
  mainapp/proj.android-studio/app/res/mipmap-hdpi/ic_launcher.png
  mainapp/proj.android-studio/app/res/mipmap-mdpi/ic_launcher.png
  mainapp/proj.android-studio/app/res/mipmap-xhdpi/ic_launcher.png
  mainapp/proj.android-studio/app/res/mipmap-xxhdpi/ic_launcher.png
  mainapp/proj.android-studio/app/res/mipmap-xxxhdpi/ic_launcher.png
Labels: enhancement

#195 Display locale specific text based on the calling application
  bookviewer/proj.android-studio/app/res/values/strings.xml
  bookviewer/proj.android-studio/app/src/com/maq/pehlaschool/library/SelectActivity.java
  bookviewer/proj.android-studio/app/src/com/maq/pehlaschool/library/SplashScreenActivity.java
Labels: bug

#198 Updated urdu splash screen images
  bookviewer/proj.android-studio/app/res/drawable-hdpi/splash_screen_background_urdu.png
  bookviewer/proj.android-studio/app/res/drawable-mdpi/splash_screen_background_urdu.png
  bookviewer/proj.android-studio/app/res/drawable-xhdpi/splash_screen_background_urdu.png
  bookviewer/proj.android-studio/app/res/drawable-xxhdpi/splash_screen_background_urdu.png
  bookviewer/proj.android-studio/app/res/drawable-xxxhdpi/splash_screen_background_urdu.png
Labels: enhancement

#199 Updated expansion file size
  bookviewer/proj.android-studio/app/main/AndroidManifest.xml
  bookviewer/proj.android-studio/app/src/kitkitschool/DownloadExpansionFile.java
Labels: enhancement

#209 Updated contact information and OBB file size
  pehlaschool/proj.android-studio/app/AndroidManifest.xml
  pehlaschool/proj.android-studio/app/res/layout/activity_about.xml
  pehlaschool/proj.android-studio/app/src/main/res/drawable-nodpi/about_image_maqsoftware.png
  pehlaschool/proj.android-studio/app/src/main/res/values/strings.xml
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/DownloadExpansionFile.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/VoiceMold.java
Labels: bug

#223 Update code to use system font for text rendering
  pehlaschool/Classes/Common/Basic/BigLabel.cpp
  pehlaschool/Classes/Common/Controls/CompletePopup.cpp
  pehlaschool/Classes/Common/Controls/TodoLoadingScene.cpp
  pehlaschool/Classes/Games/Books/BookPage.cpp
  pehlaschool/Classes/Games/ComprehensionTest/ComprehensionScene.cpp
  pehlaschool/Classes/Games/Counting/ChildNodes/AnswerPadMulti.cpp
  pehlaschool/Classes/Games/Counting/ChildNodes/AnswerPadSingle.cpp
  pehlaschool/Classes/Games/DigitalQuiz/ChildNodes/EraseDataConfirmPopup.cpp
  pehlaschool/Classes/Games/DigitalQuiz/Stages/Stage.cpp
  pehlaschool/Classes/Games/DigitalQuiz/Utils/DigitalQuizMainDepot.cpp
  pehlaschool/Classes/Games/FindTheMatch/ChildNodes/FindTheMatchCard.cpp
  pehlaschool/Classes/Games/FindTheMatch/Utils/FindTheMatchMainDepot.cpp
  pehlaschool/Classes/Games/LRComprehension/LRComprehensionScene.cpp
  pehlaschool/Classes/Games/LetterTrace/Utils/LetterTraceMainDepot.cpp
  pehlaschool/Classes/Games/MovingInsects/ChildNodes/MovingInsectsCard.cpp
  pehlaschool/Classes/Games/MovingInsects/ChildNodes/MovingInsectsGameBoard.cpp
  pehlaschool/Classes/Games/MovingInsects/Utils/MovingInsectsMainDepot.cpp
  pehlaschool/Classes/Games/MultiplicationBoard/MultiplicationBoardScene.cpp
  pehlaschool/Classes/Games/PlaceValue/PlaceValueScene.cpp
  pehlaschool/Classes/Games/ReadingBird/ReadingBirdScene.cpp
  pehlaschool/Classes/Games/Spelling/BallNodes/DummyBall.cpp
  pehlaschool/Classes/Games/Spelling/Utils/SpellingMainDepot.cpp
  pehlaschool/Classes/Games/StarFall/ChildNodes/ActiveTextNode.cpp
  pehlaschool/Classes/Games/StarFall/ChildNodes/TargetDummyNode.cpp
  pehlaschool/Classes/Games/StarFall/ChildNodes/TargetTextNode.cpp
  pehlaschool/Classes/Games/StarFall/Core/StarFallScene.cpp
  pehlaschool/Classes/Games/StarFall/Utils/StarFallDepot.cpp
  pehlaschool/Classes/Games/WhatIsThis/WhatIsThisCard.cpp
  pehlaschool/Classes/Games/WordMachine/LetterWheel.cpp
  pehlaschool/Classes/Games/WordMachine/WordMachineScene.cpp
  pehlaschool/Classes/Games/WordMatrix/WordMatrixScene.cpp
  pehlaschool/Classes/Games/WordMatrix/WordMatrixScene.h
  pehlaschool/Classes/Games/WordTrace/Utils/WordTraceMainDepot.cpp
  pehlaschool/Classes/Games/WordWindow/WordWindowScene.cpp
  pehlaschool/Classes/Managers/LanguageManager.cpp
  pehlaschool/Classes/Menu/CoopScene.cpp
  pehlaschool/Classes/Menu/CoopScene2.cpp
  pehlaschool/Classes/Menu/DailyScene.cpp
  pehlaschool/Classes/Menu/DailyScene2.cpp
  pehlaschool/Classes/Menu/GameSelectScene.cpp
  pehlaschool/Classes/Menu/GradeSelector.cpp
  pehlaschool/Classes/Menu/LevelOpenPopup.cpp
  pehlaschool/Classes/Menu/MainScene.cpp
  pehlaschool/Classes/Utils/TodoUtil.cpp
  pehlaschool/Classes/Utils/TodoUtil.h
Labels: enhancement

#225 Added Bengali support
  pehlaschool/Classes/Common/Controls/CompletePopup.cpp
  pehlaschool/Classes/Common/Controls/TodoLoadingScene.cpp
  pehlaschool/Classes/Games/ComprehensionTest/CompTrace/Core/CompTraceScene.cpp
  pehlaschool/Classes/Games/ComprehensionTest/FillTheBlanks/FillTheBlanksScene.cpp
  pehlaschool/Classes/Games/ComprehensionTest/Matching/MatchingScene.cpp
  pehlaschool/Classes/Games/ComprehensionTest/MultipleChoices/MultipleChoicesScene.cpp
  pehlaschool/Classes/Games/ComprehensionTest/Reordering/ReorderingScene.cpp
  pehlaschool/Classes/Games/Counting/ChildNodes/AnswerPadMulti.cpp
  pehlaschool/Classes/Games/Counting/ChildNodes/AnswerPadSingle.cpp
  pehlaschool/Classes/Games/LRComprehension/LRAllInOneTypeQuestion/LRAllInOneTypeQuestionScene.cpp
  pehlaschool/Classes/Games/LRComprehension/LRComprehensionScene.cpp
  pehlaschool/Classes/Games/LRComprehension/LRDividedTypeFillTheBlanks/LRDividedTypeFillTheBlanksScene.cpp
  pehlaschool/Classes/Games/LRComprehension/LRDividedTypeQuestion/LRDividedTypeQuestionScene.cpp
  pehlaschool/Classes/Games/LRComprehension/LRDividedTypeReordering/LRDividedTypeReorderingScene.cpp
  pehlaschool/Classes/Games/LetterMatching/LetterMatchingScene.cpp
  pehlaschool/Classes/Games/LetterTrace/Utils/LetterTraceMainDepot.cpp
  pehlaschool/Classes/Games/NumberMatching/NumberMatchingScene.cpp
  pehlaschool/Classes/Games/WordTrace/Utils/WordTraceMainDepot.cpp
  pehlaschool/Classes/Managers/LanguageManager.cpp
  pehlaschool/Classes/Menu/DailyScene2.cpp
  pehlaschool/Classes/Menu/GradeSelector.cpp
  pehlaschool/proj.android-studio/app/AndroidManifest.xml
  pehlaschool/proj.android-studio/app/build.gradle
  pehlaschool/proj.android-studio/app/src/bengali/res/drawable-hdpi/splash_screen_background.png
  pehlaschool/proj.android-studio/app/src/bengali/res/drawable-mdpi/splash_screen_background.png
  pehlaschool/proj.android-studio/app/src/bengali/res/drawable-nodpi/launcher_pehlaschool_logo.png
  pehlaschool/proj.android-studio/app/src/bengali/res/drawable-xhdpi/splash_screen_background.png
  pehlaschool/proj.android-studio/app/src/bengali/res/drawable-xxhdpi/splash_screen_background.png
  pehlaschool/proj.android-studio/app/src/bengali/res/drawable-xxxhdpi/splash_screen_background.png
  pehlaschool/proj.android-studio/app/src/bengali/res/mipmap-hdpi/ic_launcher.png
  pehlaschool/proj.android-studio/app/src/bengali/res/mipmap-mdpi/ic_launcher.png
  pehlaschool/proj.android-studio/app/src/bengali/res/mipmap-xhdpi/ic_launcher.png
  pehlaschool/proj.android-studio/app/src/bengali/res/mipmap-xxhdpi/ic_launcher.png
  pehlaschool/proj.android-studio/app/src/bengali/res/mipmap-xxxhdpi/ic_launcher.png
  pehlaschool/proj.android-studio/app/src/bengali/res/values/strings.xml
  pehlaschool/proj.android-studio/app/src/hindi/res/values/array.xml
  pehlaschool/proj.android-studio/app/src/hindi/res/values/colors.xml
  pehlaschool/proj.android-studio/app/src/hindi/res/values/dimens.xml
  pehlaschool/proj.android-studio/app/src/hindi/res/values/ids.xml
  pehlaschool/proj.android-studio/app/src/hindi/res/values/styles.xml
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/DownloadExpansionFile.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/VoiceMoldManager.java
  pehlaschoollibrary/proj.android-studio/app/main/AndroidManifest.xml
  pehlaschoollibrary/proj.android-studio/app/res/values/strings.xml
Labels: enhancement

#240 Updated library images for Bengali and launcher title
  pehlaschool/proj.android-studio/app/src/bengali/res/drawable-nodpi/launcher_pehlaschool_logo.png
  pehlaschool/proj.android-studio/app/src/bengali/res/values/strings.xml
  pehlaschoollibrary/proj.android-studio/app/res/drawable-hdpi/splash_screen_background_bengali.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-mdpi/splash_screen_background_bengali.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-xhdpi/splash_screen_background_bengali.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-xxhdpi/splash_screen_background_bengali.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-xxxhdpi/splash_screen_background_bengali.png
Labels: enhancement

#245 Add English, Urdu, and Bengali app info in privacy policy
  PehlaSchool-Privacy-Policy.pdf
Labels: enhancement

#244 Added exclamation mark in the Regex
  pehlaschool/Classes/Games/EggQuiz/DragButton.cpp
  pehlaschool/Classes/Games/EggQuiz/EggQuizScene.cpp
  pehlaschool/Classes/Games/EggQuiz/PushButton.cpp
  pehlaschool/Classes/Managers/LanguageManager.cpp
  pehlaschool/Classes/Utils/TodoUtil.cpp
  pehlaschool/proj.android-studio/app/src/english/res/drawable-hdpi/splash_screen_background.png
  pehlaschool/proj.android-studio/app/src/english/res/drawable-mdpi/splash_screen_background.png
  pehlaschool/proj.android-studio/app/src/english/res/drawable-nodpi/launcher_pehlaschool_logo.png
  pehlaschool/proj.android-studio/app/src/english/res/drawable-xhdpi/splash_screen_background.png
  pehlaschool/proj.android-studio/app/src/english/res/drawable-xxhdpi/splash_screen_background.png
  pehlaschool/proj.android-studio/app/src/english/res/drawable-xxxhdpi/splash_screen_background.png
  pehlaschool/proj.android-studio/app/src/english/res/mipmap-hdpi/ic_launcher.png
  pehlaschool/proj.android-studio/app/src/english/res/mipmap-mdpi/ic_launcher.png
  pehlaschool/proj.android-studio/app/src/english/res/mipmap-xhdpi/ic_launcher.png
  pehlaschool/proj.android-studio/app/src/english/res/mipmap-xxhdpi/ic_launcher.png
  pehlaschool/proj.android-studio/app/src/english/res/mipmap-xxxhdpi/ic_launcher.png
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/DownloadExpansionFile.java
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/VoiceMoldManager.java
  pehlaschoollibrary/proj.android-studio/app/res/drawable-hdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-mdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-xhdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-xxhdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/drawable-xxxhdpi/splash_screen_background.png
  pehlaschoollibrary/proj.android-studio/app/res/mipmap-hdpi/ic_launcher.png
  pehlaschoollibrary/proj.android-studio/app/res/mipmap-mdpi/ic_launcher.png
  pehlaschoollibrary/proj.android-studio/app/res/mipmap-xhdpi/ic_launcher.png
  pehlaschoollibrary/proj.android-studio/app/res/mipmap-xxhdpi/ic_launcher.png
  pehlaschoollibrary/proj.android-studio/app/res/mipmap-xxxhdpi/ic_launcher.png
Labels: bug

#247 Fix issue with standalone installation of Library app
  pehlaschoollibrary/Classes/AppDelegate.cpp
  pehlaschoollibrary/Classes/BookView.cpp
  pehlaschoollibrary/proj.android-studio/app/res/values/strings.xml
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/pehlaschool/library/MainActivity.java
  pehlaschoollibrary/proj.android-studio/app/src/com/maq/pehlaschool/library/SelectActivity.java
Labels: bug

#246 Update path name and version code
  pehlaschool/Classes/Games/ReadingBird/ReadingBirdScene.cpp
  pehlaschool/Classes/Managers/LanguageManager.cpp
  pehlaschool/proj.android-studio/app/AndroidManifest.xml
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/DownloadExpansionFile.java
Labels: enhancement

#248 Update Learning module's OBB size
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/DownloadExpansionFile.java
Labels: enhancement

#249 Updated Learning module's OBB file size
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/DownloadExpansionFile.java
Labels: bug

#250 Updated version code number
  pehlaschoollibrary/proj.android-studio/app/main/AndroidManifest.xml
Labels: enhancement

#254 Updated version code in Download expansion file
  pehlaschoollibrary/proj.android-studio/app/src/kitkitschool/DownloadExpansionFile.java
Labels: enhancement

#255 Change position of Urdu app title
  PehlaSchool-Privacy-Policy.pdf
Labels: minor fix

#257 Add 64-bit support for Library app
  pehlaschoollibrary/proj.android-studio/app/jni/Application.mk
  pehlaschoollibrary/proj.android-studio/gradle.properties
Labels: enhancement

#256 Update book data path in Library and remove 'en-us' from games path
  pehlaschool/Classes/Games/ReadingBird/ReadingBirdScene.cpp
  pehlaschool/Classes/Managers/LanguageManager.cpp
  pehlaschool/proj.android-studio/app/AndroidManifest.xml
  pehlaschool/proj.android-studio/app/src/org/cocos2dx/cpp/DownloadExpansionFile.java
  pehlaschoollibrary/Classes/Managers/LanguageManager.cpp
  pehlaschoollibrary/proj.android-studio/app/build.gradle
  pehlaschoollibrary/proj.android-studio/app/main/AndroidManifest.xml
Labels: bug
