Repository maqsoftware/Pehla-School, pull requests merged in 2019-06, with the labels that each got.

#21 Fixed the line wrap issue with bi-lingual headings
  launcher/app/src/debug/AndroidManifest.xml
  launcher/app/src/release/AndroidManifest.xml
  mainapp/Classes/Managers/LanguageManager.cpp
  mainapp/Classes/Menu/DailyScene2.cpp
  mainapp/Classes/Menu/GameSelectScene.cpp
  mainapp/Classes/Menu/MainScene.cpp
  mainapp/proj.android-studio/app/AndroidManifest.xml
  mainapp/proj.android-studio/app/release/AndroidManifest.xml
  mainapp/proj.android-studio/app/src/main/res/layout/activity_splash_screen.xml
  mainapp/proj.android-studio/gradle/wrapper/gradle-wrapper.properties
Labels: bug

#25 Fix the boolean variable for admin mode
  mainapp/Classes/Menu/MainScene.cpp
Labels: bug

#27 Added bilingual support in splash and loading screen
  library/app/src/main/res/layout/activity_splash_screen.xml
  library/app/src/main/res/values/strings.xml
  mainapp/Classes/Common/Controls/TodoLoadingScene.cpp
  mainapp/proj.android-studio/app/src/main/res/layout/activity_splash_screen.xml
  mainapp/proj.android-studio/app/src/main/res/values/strings.xml
Labels: enhancement

#41 Fixed the app icon
  library/app/src/main/res/mipmap-hdpi/ic_launcher.png
  library/app/src/main/res/mipmap-mdpi/ic_launcher.png
  library/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  library/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  library/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  marimba/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  marimba/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  marimba/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  marimba/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  marimba/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  writingboard/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  writingboard/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  writingboard/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  writingboard/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  writingboard/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: bug

#46 Removed shared user id
  launcher/app/build.gradle
  launcher/app/src/debug/AndroidManifest.xml
  launcher/app/src/release/AndroidManifest.xml
Labels: bug

#54 Added popup to redirect to play store
  kitkitschoollogger/kitkitlogger/src/main/java/com/maq/kitkitlogger/KitKitLoggerActivity.java
  launcher/app/src/main/java/com/maq/xprize/kitkitlauncher/hindi/MainActivity.java
  launcher/app/src/main/java/com/maq/xprize/kitkitlauncher/hindi/ToolsActivity.java
  launcher/app/src/main/res/values-sw/strings.xml
  launcher/app/src/main/res/values/strings.xml
Labels: enhancement

#59 Updated the link of the writing board and dialog title
  launcher/app/build.gradle
  launcher/app/src/main/java/com/maq/xprize/kitkitlauncher/hindi/ToolsActivity.java
  launcher/app/src/main/java/com/maq/xprize/kitkitlauncher/hindi/VideoPlayerActivity.java
  launcher/app/src/main/res/values/strings.xml
Labels: bug

#74 Updated the condition to open all the modules and user can play any games any number of time
  library/app/build.gradle
  mainapp/Classes/CCAppController.cpp
  mainapp/Classes/Managers/UserManager.cpp
  mainapp/Classes/Managers/UserManager.hpp
  mainapp/Classes/Menu/CoopScene.cpp
  mainapp/Classes/Menu/GameSelectScene.cpp
  mainapp/Classes/Menu/MainScene.cpp
  mainapp/Classes/Menu/MainScene.hpp
  mainapp/proj.android-studio/app/build.gradle
  mainapp/proj.android-studio/app/src/kitkitschool/DownloadExpansionFile.java
Labels: enhancement

#94 Updated the condition to open all the games
  mainapp/Classes/Menu/DailyScene.cpp
  mainapp/Classes/Menu/DailyScene2.cpp
Labels: bug

#95 Added patch file logic to provide incremental updates
  launcher/app/src/main/java/com/maq/xprize/kitkitlauncher/hindi/MainActivity.java
  library/app/src/main/java/com/maq/xprize/kitkitlibrary/english/MainActivity.java
  library/app/src/main/java/com/maq/xprize/kitkitlibrary/english/SelectActivity.java
  library/app/src/main/java/com/maq/xprize/kitkitlibrary/english/SplashScreenActivity.java
  library/app/src/main/java/kitkitschool/DownloadExpansionFile.java
  library/app/src/main/java/utils/Zip.java
  library/app/src/main/res/layout/download_expansion_file.xml
  library/app/src/main/res/values/strings.xml
  library/downloader_library/src/main/res/values/strings.xml
  mainapp/proj.android-studio/app/AndroidManifest.xml
  mainapp/proj.android-studio/app/res/values/strings.xml
  mainapp/proj.android-studio/app/src/kitkitschool/DownloadExpansionFile.java
  mainapp/proj.android-studio/app/src/main/res/layout/download_expansion_file.xml
  mainapp/proj.android-studio/app/src/org/cocos2dx/cpp/AppActivity.java
  mainapp/proj.android-studio/app/src/org/cocos2dx/cpp/SplashScreenActivity.java
  mainapp/proj.android-studio/app/src/utils/Zip.java
  mainapp/proj.android-studio/downloader_library/src/main/res/values/strings.xml
Labels: bug, enhancement
